
quarkus:
  datasource:
    db-kind: h2
    password: password
    username: sa
    jdbc:
      driver: org.h2.Driver
      url: jdbc:h2:mem:testdb
  h2.console.enabled: true

server.port: ${PORT:9998}