
server.port: ${PORT:9999}

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      format_sql: true
      show_sql: true